### ISSUE TITLE
No need runLater method to push scene anymore.

### ISSUE THREAD

**Issue by imwithye** [Study-Master/Client#2]
While you are switching scene, no need nextView() and runLater method. Simply use `director.pushStageWithFXML(...)`. runLater thread has already been implemented in Director class.

I have merged the newest master branch into BookingView, all you need to do is update BookingView class and remove nextView method and runLater method.

**Note that you don't have to use runLater thread to pushStage, but you will still need it when you update the GUI or draw GUI dynamically.** You may ref to [this](https://github.com/Study-Master/Client/blob/51e6b19ba7ebb312bb23a5c71297ec8ad76c5904/examinee/src/main/java/studymaster/examinee/ViewController/CourseView.java) commit when you need GUI operation. You can create a runLater thread in onMessage method. If you have to access variable outside runLater method, you have to define it as `final` type.

Have fun:)

**Comment by samyro** [comment]
All hail Ciel!!!

**Comment by imwithye** [comment]
I suggest that you'd better update your JSON API in socketserver and then we team use one example server. Socketserver is hosted on [this repo](https://github.com/Study-Master/socketserver). I have fix the getHost bug. You can build it simply using `mvn clean package`. Don't forget update your JSON API to [Readme/JSON_API.md](https://github.com/Study-Master/Readme/blob/master/JSON_API.md) so that we can make sure everyone follows standards.
